\[#启动: nohup java   -Dspring.profiles.active=dev -jar synchronius-1.0.jar >  log.erp 2>&1 &
server:
  port: 8090
  compression:
    enabled: true
  connection-timeout: 3000
spring:
  redis:
    cluster:
      nodes: 192.168.0.111:7000,192.168.0.111:7001,192.168.0.111:7002,192.168.0.113:7000,192.168.0.113:7001,192.168.0.113:7002,192.168.0.117:7000,192.168.0.117:7001,192.168.0.117:7002
#  thymeleaf:
#        cache: false        #缓存
  devtools:
      restart:
        enabled: true                       #开启
        additional-paths: src/main/java     #监听目录
swagger:
  host: local.dev.com




